### ISSUE TITLE
feed:generate does not support by nitro new version.

### ISSUE THREAD

**Issue by hadimajidi** [tresko/nuxt-module-feed#44]
feed:generate does not support nitro in the new version.
any solution?

**Comment by tresko** [comment]
Works ok for me with Nitro 2.8.1. Can you link the example?

**Comment by hadimajidi** [comment]
I do not know the version of nitro, but the version of nuxt is 3.10.3.

**Comment by tresko** [comment]
Checkout our playground it uses Nuxt 3.10.3 and it works ok.

**Comment by hadimajidi** [comment]
![nitro](https://github.com/tresko/nuxt-module-feed/assets/28122641/fd8fa338-6c79-43d4-b0b6-a8b5a4341d3c)
check it out please

**Comment by tresko** [comment]
Please try https://github.com/tresko/nuxt-module-feed/releases/tag/v1.1.4 it should be fixed.

**Comment by hadimajidi** [comment]
the problem still exists.
![nitro1](https://github.com/tresko/nuxt-module-feed/assets/28122641/0527a283-2d1a-4d50-9ea1-f20a18a1f451)
